# Compilation
configure-args-y += --enable-maintainer-mode
compile: default-autotools-compile

# Installation
staging: default-autotools-staging

rootfs: default-copyall-rootfs

clean: default-clean

confcheck: default-confcheck
