configure-args-y += \
	--with-rpcuser=daemon

rootfs-y += \
	/usr/bin/rpcbind \
	/usr/bin/rpcinfo

compile: default-autotools-compile

staging: default-autotools-staging

rootfs: default-rootfs

clean: default-clean
