#! /bin/sh

if test -n "$MODALIAS"; then
    modprobe "$MODALIAS"
fi
if test -n "$IFINDEX" -a "$INTERFACE" != "eth0"; then
    ifconfig "$INTERFACE" up 0.0.0.0
    udhcpc -a -b -R -S -i "$INTERFACE"
fi
exec /sbin/mdev
