#! /bin/sh

server=`dmesg | sed 's/^.*rootserver=\([^,]*\).*$/\1/;t;d'`

test -e /proc/sys/kernel/hung_task_timeout_secs && \
echo 0 > /proc/sys/kernel/hung_task_timeout_secs

seq 1 399999 > /tmp/netcat.data
( while :; do cat /tmp/netcat.data ; sleep 15; done | netcat -vv -l -p 5566 ) &
a=$!
( while :; do cat /proc/interrupts > /dev/null; done ) &
b=$!
( while :; do ps w > /dev/null; done ) &
c=$!

cd /ltp && ./runalltests.sh
cd /ltp && ./runalltests.sh
kill -9 $a $b $c
rm -f /tmp/netcat.data
killall -INT latency
