configure-args-y += --without-zlib --without-expat --with-curses

compile: default-autotools-compile

staging: default-autotools-staging

rootfs-y := /usr/bin/gdb

rootfs: default-rootfs

clean: default-clean
