#! /bin/ash

mount /proc
echo /sbin/mdev > /proc/sys/kernel/hotplug
mount -a
MDEV= @MKR_MOUNT_DEV@ /sbin/mount_storage.sh &

if test ! -e /etc/ld.so.cache; then
    echo -n 'Running ldconfig...'
    ldconfig
    echo done
fi

/usr/sbin/rdate -s `dmesg | sed 's/^.*rootserver=\([^,]*\).*$/\1/;t;d'`

mkdir -p /var/log
syslogd -S -D -L
klogd
telnetd

if test -e /ltp && test ! -e /ltp/.installed -o ! -e /ltp/testcases/bin/hackbench; then
    echo 'Installing LTP'
    dir=`pwd`
    cd /ltp
    make install && : > /ltp/.installed
    cd $dir
fi

if test -e /lib/modules/`uname -r`/modules.dep.bb; then
    rm /lib/modules/`uname -r`/modules.dep.bb
fi

chown root:0 /bin/ping
chmod u+sx /bin/ping
