configure-args-y += \
	ac_cv_path_PCAP_CONFIG="" \
	ac_cv_path_ac_pt_PCAP_CONFIG="" \
	ac_cv_linux_vers=2 \
	--without-crypto

rootfs-y += /usr/sbin/tcpdump

compile: default-autotools-compile

staging: default-autotools-staging

rootfs: default-rootfs

clean: default-clean
